### ISSUE TITLE
error with this version, old one working fine with same yml

### ISSUE THREAD

**Issue by zalim1** [erkexzcx/stalkerhek#11]
~/stalkerhek# ./stalkerhek
2021/03/25 13:46:36 main.go:28: Connecting to Stalker middleware...
2021/03/25 13:46:36 main.go:30: Get "?type=stb&action=handshake&prehash=0&token=0DEF849B0E17E8D8D9060F879BBEC665&JsHttpRequest=1-xml": unsupported protocol scheme ""

**Comment by erkexzcx** [comment]
I've changed configuration file a bit. You should check if you have `url:` instead of `portal_url:`: https://github.com/erkexzcx/stalkerhek/blob/master/stalkerhek.example.yml#L10

**Comment by erkexzcx** [comment]
It's actually my fault that I forgot this check :D https://github.com/erkexzcx/stalkerhek/commit/0361be745e0db1696583f9097567c8fc4864301a

**Comment by zalim1** [comment]
Fixed, working now
Thanks

**Comment by erkexzcx** [comment]
Nice to hear. I will leave this issue opened for a week or so, so other people coming here can find the solution.

**Comment by zalim1** [comment]
http://some.com:9999/iptv
is this restricted to vlc only?

**Comment by erkexzcx** [comment]
No, not restricted. VLC is the most popular "watch it right away" player out there, this is why I am mentioning it a lot.

It's HLS playlist (also known as M3U) which can be opened with VLC and it shows channels list. :) For example, it could be opened with Kodi using "Simple IPTV" PVR addon, added in Jellyfin media center as Live TV content or addes to Movian player (I've had this player on jailbroken PS3).

**Comment by erkexzcx** [comment]
Note that underlaying channels, from what I've observed in all tested 4 Stalker portals, are provided in HLS format.

That URL is just HLS playlist. :)

**Comment by zalim1** [comment]
can you make it wait little more for channel list

  string(2) "OK"
  ["results"]=>
  bool(true)
}
generated in: 0.808s; query counter: 7; cache hits: 0; cache miss: 0; php errors: 0; sql errors: 0;
2021/03/28 09:40:56 main.go:34: Retrieving channels list from Stalker middleware...
2021/03/28 09:41:06 main.go:37: context deadline exceeded (Client.Timeout or context cancellation while reading body)

**Comment by erkexzcx** [comment]
Sure. Let me check what I can do.

**Comment by erkexzcx** [comment]
Done. Increased from 10 seconds to 5 minutes.

**Comment by zalim1** [comment]
change you made worked good.
its working and back up now, thanks

**Comment by zalim1** [comment]
i dont know if this is right question or not
just want to ask in the link where we get %20 for space
can we get _ under square 
example right know we get "channel%20BB" can we get  "channel_BB"
thanks

**Comment by erkexzcx** [comment]
Hi. It's not possible, because `channel BB` and `channel_BB` are 2 different channels. :)

Wondering why are you asking this? All applications show those channels perfectly fine, with space instead of `%20`. 🤔

**Comment by zalim1** [comment]
My android phone chrome browser showing black screen, vlc playing ok
Link emailed

**Comment by erkexzcx** [comment]
Not related to Stalkerhek because your Android's browser does not play. Please use VLC for this. I have no plans for reencoding streams or anything like that.
