### ISSUE TITLE
How to 

### ISSUE THREAD

**Issue by ghostboy2112** [erkexzcx/stalkerhek#14]
how to use this. please help.

**Comment by erkexzcx** [comment]
# Step 1
![image](https://user-images.githubusercontent.com/5955795/114360817-1f679a00-9b7e-11eb-9aa3-6a7c2bbbf83b.png)


# Step 2
![image](https://user-images.githubusercontent.com/5955795/114360854-2db5b600-9b7e-11eb-9cb5-c7785b530e22.png)

If you still fail to understand how to use it - then you shouldn't be using this application.
