### ISSUE TITLE
(help) Mac based login STB configuration

### ISSUE THREAD

**Issue by rockydares** [erkexzcx/stalkerhek#19]
Straight to the point, So, mac based stb doesn't require username password and I did sniff http packet from my mac based iptv, Can someone please give and idea to modify the script and make it work for my iptv portal? (This would help many cause most of them use this type iptv)

> GET /stalker_portal/server/load.php?type=stb&action=handshake&token=&prehash=9c42ac937c6bc42ba21b45b853bfc020b013f8f6&JsHttpRequest=1-xml HTTP/1.1
Cookie: mac=00%3A1A%3A79%3A22%3A00%3A12; stb_lang=en; timezone=Europe%2FLondon; adid=7be88d36cf378912b9216ba1373ec958
Referer: http://123.123.123.123/stalker_portal/c/
Accept: */*
User-Agent: Mozilla/5.0 (QtEmbedded; U; Linux; C) AppleWebKit/533.3 (KHTML, like Gecko) MAG200 stbapp ver: 2 rev: 250 Safari/533.3
X-User-Agent: Model: MAG250; Link: WiFi
Cache-Control: no-cache
Host: 123.123.123.123
Connection: Keep-Alive
Accept-Encoding: gzip

There is no GET named  "**do_auth**" as seen in **"authetication.go**" file. After handshake direct channel list showing

Kindly help me to make a proper **stalkerhek.yml** configuration.

**Comment by erkexzcx** [comment]
> So, mac based stb doesn't require username password

Just do not set `username` and `password` fields (either leave them empty, or remove these fields completelly).

Let me know if it still doesn't work.
