### ISSUE TITLE
envo go : no such directory or file

### ISSUE THREAD

**Issue by ciaranmcg17** [erkexzcx/stalkerhek#2]
Hey, 

I know 'go' programming language must be installed. i am receiving the following error when I try to build:

env: 'go': No such file or directory 

I then install the golang using _apt-get install golang_ , once I try rebuilding with ./build.sh I receive the following error:

I get several errors like below:

$GOPATH not set

cmd/stalkerhek/main.go:11:2 cannot find package "github.com/erkexzcx/stalkerhek/pkg/stalker/" in any of /usr/lib/go-1.6/src/github.com/erkexzcx/stalkerhek/pkg/stalker/" (from $GOROOT).

Can you please advise? 

Happy Christmas.

**Comment by erkexzcx** [comment]
What's the output of:
```
go -version
```

That's right, go is not installed. :) Otherwise it's not configured properly and `go` doesn't work.

**Comment by ciaranmcg17** [comment]
Yeah, I receive error saying it's not installed. I don't get a specific output until i type:
`go version`

output is.. 
`go version go1.6.2 linux/amd64
`
maybe i have installed the wrong go?

Can you advise how to install go with correct directory to work with your script?

**Comment by erkexzcx** [comment]
Well, it says `$GOPATH` not found, so you basically need to export it. Please check online how to fix it.

Also I should have mentioned that golang in official repos is usually very outdated. Get it from https://golang.org/dl/ instead (during the setup you will also setup `$GOPATH` too). Search online for tutorials. :)
