### ISSUE TITLE
Fail to update channel

### ISSUE THREAD

**Issue by aplayerv1** [erkexzcx/stalkerhek#5]
request_iptv.go:25: Failed to update channel: Stalker portal returned invalid link to TV Channel: stalker portal returned invalid link to tv channel: http///xxxxxxxxxxxxx ............... although the link works

**Comment by erkexzcx** [comment]
Please provide more information on this. Like link URL etc.

**Comment by aplayerv1** [comment]
Sorry i fixed it works create

**Comment by zalim1** [comment]
> Sorry i fixed it works great

how did you fix this?
i am getting same msg when i connect to server without username and pass
but when i use username and pass which is right one, dosent connect saying  invalid credentials

**Comment by erkexzcx** [comment]
> Sorry i fixed it works great

Then closing it :)

**Comment by aplayerv1** [comment]
> > Sorry i fixed it works great
> 
> how did you fix this?
> i am getting same msg when i connect to server without username and pass
> but when i use username and pass which is right one, dosent connect saying invalid credentials

Edit channels.go file

go to line 45
and comment out  return "", errors.New("Stalker portal returned invalid link to TV Channel: " + tmp.Js.Cmd)

and replace it with 

return tmp.Js.Cmd, nil

thats how i fixed it
