### ISSUE TITLE
./stalkerhek_linux_x86_64 2021/03/21 09:36:03 main.go:46: invalid credentials

### ISSUE THREAD

**Issue by zalim1** [erkexzcx/stalkerhek#7]
need help please, dont know why i am getting this error msg

device_id=4427E82C0C0ECD9B451F5F6FBBBFBF853363D21975808A97AC55EA6FA69D6ED2&device_id2=A211D5558B5F4B378E78310AA12D7502BF38CE49B5ACC25AE9FD013AAA501048&signature=vsYtYYLrAuylw3IqOoEIb5XbrujdsQdAR/AxyO1ZRiQ=&auth_second_step=1&hw_version=1.7-BD-00&not_valid_token=0&JsHttpRequest=1-xml HTTP/1.1
Cookie: __cfduid=ddca3b6d4ceee39e20e5c20de1bb01fca1616242567

model: MAG250
serial_number: yes13 numbers
device_id: 4427E82C0C0ECD9B451F5F6FBBBFBF853363D21975808A97AC55EA6FA69D6ED2
device_id2: A211D5558B5F4B378E78310AA12D7502BF38CE49B5ACC25AE9FD013AAA501048
signature: vsYtYYLrAuylw3IqOoEIb5XbrujdsQdAR/AxyO1ZRiQ=
mac: yes valid mac
username: yes login
password: yes pass
portal_url: http://info.com/stalker_portal/server/load.php
time_zone: America/Toronto
token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

**Comment by erkexzcx** [comment]
It fails to authenticate. Can't be sure, but here it is: https://github.com/erkexzcx/stalkerhek/blob/master/pkg/stalker/authentication.go#L71

**Comment by zalim1** [comment]
ok, finally i am able to start it but channels not working...... if i put user and pass it gives me invalid credentials error, without user and pass it works but channel dosent work.
and i am 100% sure that user and pass i am using is right

**Comment by erkexzcx** [comment]
I can't advise on this without knowing further details. Can you send me your details to my email erikmnkl@gmail.com?

More or less provide what wireshark shows (e.g. full URLs) and what you put into YAML file. Maybe I am missing something, maybe you are missing something... Without knowing more details I can't advise.

**Comment by zalim1** [comment]
details sent

**Comment by erkexzcx** [comment]
With latest commits I think I've fixed 2 separate issues that caused stream to stop after short period of time (few to ~30 seconds). Please check against latest code in this repo and if it still doesn't work - open a new issue.
