### ISSUE TITLE
error while installation

### ISSUE THREAD

**Issue by zalim1** [erkexzcx/stalkerhek#8]
stalkerhek-master# go build -ldflags="-s -w" -o "stalkerhek" ./cmd/stalkerhek/main.go
cmd/stalkerhek/main.go:7:2: cannot find package "github.com/erkexzcx/stalkerhek/proxy" in any of:
	/usr/lib/go-1.10/src/github.com/erkexzcx/stalkerhek/proxy (from $GOROOT)
	/root/go/src/github.com/erkexzcx/stalkerhek/proxy (from $GOPATH)
cmd/stalkerhek/main.go:8:2: cannot find package "github.com/erkexzcx/stalkerhek/stalker" in any of:
	/usr/lib/go-1.10/src/github.com/erkexzcx/stalkerhek/stalker (from $GOROOT)
	/root/go/src/github.com/erkexzcx/stalkerhek/stalker (from $GOPATH)

**Comment by zalim1** [comment]
i tried https://github.com/erkexzcx/stalkerhek/tree/master/proxy in main.go
but no luck

**Comment by erkexzcx** [comment]
I will update instructions shortly. Please use latest golang from website, because in official repos it's always so freaking out of date that it's unusable. See https://golang.org/doc/install for instructions.
